# Generated by Django 5.0 on 2025-12-06 01:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Categoria Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRODUTO', 'Produto Físico'), ('SERVICO', 'Serviço/Mão de Obra')], max_length=10, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Item')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('preco_venda', models.DecimalField(decimal_places=2, help_text='Preço cobrado do cliente', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço de Venda (R$)')),
                ('custo_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quanto custa para você (produto) ou tempo (serviço)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Custo Base (R$)')),
                ('estoque_atual', models.IntegerField(default=0, help_text='Quantidade disponível (deixe 0 para serviços)', verbose_name='Estoque Atual')),
                ('estoque_minimo', models.IntegerField(default=0, help_text='Alerta quando atingir este valor', verbose_name='Estoque Mínimo')),
                ('unidade_medida', models.CharField(default='UN', help_text='Ex: UN, KG, L, ML, M', max_length=20, verbose_name='Unidade de Medida')),
                ('visivel_no_site', models.BooleanField(default=False, help_text='Aparece na vitrine pública?', verbose_name='Visível no Site')),
                ('visivel_no_zap', models.BooleanField(default=True, help_text='Aparece no catálogo do bot?', verbose_name='Visível no WhatsApp')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='catalogo/', verbose_name='Imagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Item Ativo')),
                ('destaque', models.BooleanField(default=False, help_text='Aparece primeiro nas listagens', verbose_name='Item em Destaque')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='catalogo.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Item do Catálogo',
                'verbose_name_plural': 'Itens do Catálogo',
                'ordering': ['-destaque', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, help_text='Ex: 50 (se a unidade for ML), 1 (se for UN)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantidade Consumida')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('produto_filho', models.ForeignKey(limit_choices_to={'tipo': 'PRODUTO'}, on_delete=django.db.models.deletion.PROTECT, related_name='usado_em_servicos', to='catalogo.itemcatalogo', verbose_name='Produto/Insumo')),
                ('servico_pai', models.ForeignKey(limit_choices_to={'tipo': 'SERVICO'}, on_delete=django.db.models.deletion.CASCADE, related_name='insumos_necessarios', to='catalogo.itemcatalogo', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Consumo de Insumo',
                'verbose_name_plural': 'Consumos de Insumos',
            },
        ),
        migrations.AddIndex(
            model_name='itemcatalogo',
            index=models.Index(fields=['tipo', 'ativo'], name='catalogo_it_tipo_6045ee_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcatalogo',
            index=models.Index(fields=['visivel_no_site', 'ativo'], name='catalogo_it_visivel_f23141_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='consumoinsumo',
            unique_together={('servico_pai', 'produto_filho')},
        ),
    ]
